/* Article Actions */
export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_NEW_ARTICLE = "SET_NEW_ARTICLE";
export const EDIT_ARTICLE = "EDIT_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const GET_ARTICLES = "GET_ARTICLES";
export const SET_ARTICLES = "SET_ARTICLES";
export const GET_ARTICLE_DETAILS = "GET_ARTICLE_DEATILS";
export const SET_ARTICLE_DETAILS = "SET_ARTICLE_DETAILS";

/* Comment Actions */
export const ADD_COMMENT = "ADD_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS";
export const SET_COMMENTS = "SET_COMMENTS";

/* User Actions */
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHECK_LOGGEDIN = "CHECK_LOGGEDIN";
export const SET_LOGGEDIN = "SET_LOGGEDIN";

